### ISSUE TITLE
Core 3.0 and EF 6.3 Dependency

### ISSUE THREAD

**Issue by fgather** [neisbut/EntityFramework.MemoryJoin#11]
With Core 3.0 it is possible to make use of EF6.3. Unfortunately, the EF6 version of MemoryJoin is not compatible yet. Do you have any plans to change that?

**Comment by neisbut** [comment]
Hi @fgather, yes, definitely going to do that!

**Comment by neisbut** [comment]
Hi @fgather, took some time, but I did it. Since EF6.3 also works with .Net Standard I extracted it into a separate package `EntityFrameworkCore.MemoryJoin.Ef6`. Please check when possible.

**Comment by fgather** [comment]
Awesome, looks like it works for my use-case! Thanks for the quick response ;)
