### ISSUE TITLE
Variable insert limit 2100 error

### ISSUE THREAD

**Issue by Eits-Ian** [neisbut/EntityFramework.MemoryJoin#13]
If you try to insert more than 2100 itemes in the FromLocalList it will error and you will need to batch and concat before the query. I tried the same using Thinktecture.EntityFrameworkCore.SqlServer BulkInsertValuesIntoTempTableAsync which worked with greater than the 2100 limit.

**Comment by neisbut** [comment]
Hi @Eits-Ian, please try calling FromLocalList with specifying ValuesInjectionMethod.ViaSqlQueryBody like this:

    var query = context.FromLocalList(data, ValuesInjectionMethod.ViaSqlQueryBody);

Please let me know if that helps.

**Comment by Eits-Ian** [comment]
Hi Anton,

That was the first thing I did making it implicit however no difference.

**Comment by neisbut** [comment]
@Eits-Ian , hm, that is weird. Can provide more details please? What EF version, what entity and mapping was used? I will try to replicate on my side.

**Comment by neisbut** [comment]
Closed due to inactivity
