### ISSUE TITLE
.NET5

### ISSUE THREAD

**Issue by geebacsi** [neisbut/EntityFramework.MemoryJoin#17]
Hi,

Do you plan to upgrade to .NET5?
In .NET CORE 3 the RawSqlString was obsolete, and in .NET5, it can not be used.

Thanks,
Gábor

**Comment by neisbut** [comment]
Hi @geebacsi, yes, of course. It was in my plan and actually was released today in 0.7.5 version, so you can try now.

**Comment by geebacsi** [comment]
waaaoooo, thanks for the very fast solution. I will check it...

**Comment by geebacsi** [comment]
it works :), thank you
