### ISSUE TITLE
Nuget Package not up to date

### ISSUE THREAD

**Issue by fgather** [neisbut/EntityFramework.MemoryJoin#3]
Hi,

first of all: thanks for the great library!
I've got an issue with empty lists I want to join to and I suspect you already fixed it with your latest commit. However, I cannot benefit from the fix, since the nuget package is outdated. Do you have any plans to update it soon?

Many Regards,
Florian

**Comment by los93sol** [comment]
I'd like to second the thanks for the library, it has helped me out with some issues I was facing, but I am also in the same boat and need the fixes for empty lists to continue moving forward

**Comment by neisbut** [comment]
Hi guys, omg, I thought I published it! It seems I forgot! Will do it just now! Sorry for waiting for so long time.
