### ISSUE TITLE
Issue with OrderBy and table splitting in a M 2 M relashionship - it creates a duplicate OrderBy entry

### ISSUE THREAD

**Issue by Eits-Ian** [neisbut/EntityFramework.MemoryJoin#9]
If you have an entity with a many to many relationship which is in a split table entity and you want this list included in your projection it duplicates the OrderBy.

**Comment by neisbut** [comment]
Hi @Eits-Ian, could you please provide a bit more details on what setup do you have?

**Comment by neisbut** [comment]
Closed due to inactivity
